version: '3.9'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 96wo784W
      POSTGRES_DB: clinic
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    build: ./app
    ports:
      - "5000:5000"
    environment:
      DB_HOST: 192.168.0.103
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 96wo784W
      DB_NAME: clinic
      DATABASE_URL: postgresql://postgres:96wo784W@db:5432/clinic
      FLASK_ENV: development
    depends_on:
      - db
    working_dir: /app
    command: python main.py
    volumes:
      - ./app:/app
