version: '3.8'

services:
  web:
    build: .
    container_name: clinic_web
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:96wo784W@db:5432/clinic
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: clinic_db
    restart: always
    environment:
      POSTGRES_DB: clinic
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 96wo784W
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
